const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright'),assert=require('assert');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH || undefined,headless:true,args:['--no-sandbox']});try{const context=await browser.newContext({viewport:{width:1440,height:960},reducedMotion:'reduce'});const login=await fetch('http://127.0.0.1:17663/api/portal/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'alex.updated',password:'Changed-Workspace-123!'})}).then(r=>r.json());assert(login.success,login.message);await context.addInitScript(data=>Object.entries(data).forEach(([k,v])=>sessionStorage.setItem(k,typeof v==='object'?JSON.stringify(v):String(v))),login.data);const p=await context.newPage(),errors=[],failed=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().includes('/api/portal/core')&&r.status()>=400)failed.push(r.url()+': '+r.status());});
await p.goto('http://127.0.0.1:7201/admin/organization');await p.locator('[role=treeitem]').first().waitFor();await p.evaluate(()=>window.treeNode=document.querySelector('[role=treeitem]'));await p.getByRole('button',{name:'Expand all',exact:true}).hover();await p.waitForTimeout(600);assert(await p.evaluate(()=>window.treeNode===document.querySelector('[role=treeitem]')),'Tree row identity changed during idle/hover');const count=await p.locator('[role=treeitem]').count();await p.getByRole('button',{name:'Collapse all',exact:true}).click();assert((await p.locator('[role=treeitem]').count())<count,'Collapse did not hide a child');await p.getByRole('button',{name:'Expand all',exact:true}).click();assert.equal(await p.locator('[role=treeitem]').count(),count);
await p.getByRole('textbox',{name:'Search reporting network'}).fill('employee Test');assert((await p.locator('[role=treeitem]').count())>=2,'Matching descendants must retain ancestors');await p.getByRole('button',{name:'Collapse all',exact:true}).click();assert.equal(await p.locator('[role=treeitem]').count(),1,'Collapse must work with an active filter');await p.getByRole('button',{name:'Expand all',exact:true}).click();await p.getByRole('textbox',{name:'Search reporting network'}).fill('');
for(const width of [390,768,1440]){await p.setViewportSize({width,height:960});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'Organization overflow '+width);}await p.setViewportSize({width:1440,height:960});
for(const module of ['people','attendance','leave','documents','messages','events','engagement','exit','salary','approvals','audit','policies']){await p.goto('http://127.0.0.1:7201/admin/hr/'+module);await p.locator('.module-summary').first().waitFor();assert(await p.locator('.nav-group > ng-container').count()===0);const main=p.locator('.nav-group a.active[href="/admin/hr/'+module+'"]');assert.equal(await main.count(),1,'Module navigation active: '+module);const tabs=p.locator('.core-tabs button');const total=await tabs.count();for(let i=1;i<total;i++){await tabs.nth(i).click();await p.locator('.core-report').waitFor();await p.waitForFunction(()=>document.querySelector('.core-report').getAttribute('aria-busy')==='false');assert.equal(await main.count(),1,'Tab cleared active module: '+module);if(await p.getByRole('button',{name:'Add new',exact:true}).count()){await p.getByRole('button',{name:'Add new',exact:true}).click();await p.locator('.core-form').waitFor();assert.equal(await p.locator('.core-report').count(),0,'Entry and reports must be separate views');await p.getByRole('button',{name:'Close form'}).click();await p.locator('.core-report').waitFor();}}console.log('PASS views/tabs: '+module);}
await p.goto('http://127.0.0.1:7201/admin/hr/people?tab=assignments&view=reports');await p.locator('.core-report').waitFor();await p.waitForFunction(()=>document.querySelector('.core-report').getAttribute('aria-busy')==='false');const search=p.getByRole('textbox',{name:'Search records'});await search.fill('Engineering');await p.evaluate(()=>window.reportInput=document.querySelector('.core-report input'));await search.press('Enter');await p.waitForFunction(()=>document.querySelector('.core-report').getAttribute('aria-busy')==='false');assert(await p.evaluate(()=>window.reportInput===document.querySelector('.core-report input')&&document.activeElement===window.reportInput),'Filter recreated input/lost focus');
await p.goto('http://127.0.0.1:7201/admin/profile-settings');await p.getByText('HR notification delivery',{exact:true}).waitFor();assert(await p.getByRole('checkbox',{name:'SMS notifications'}).count());assert.equal(errors.length,0,errors.join('\n'));assert.equal(failed.length,0,failed.join('\n'));console.log('PASS: stable tree identity, filtered expand/collapse, responsive filters, dashboards/entry/reports, active navigation, report-only refresh preserves focus, and delivery preferences.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});


